import re

def sustituir_abreviaturas(content):
    ROMANO = r'((CM|CD|D?C?C?C?)(XC|XL|L?X?X?X?)(IX|IV|VI?I?I?|II?I?)|(CM|CD|D?C?C?C?)(XC|XL|LX?X?X?|XX?X?)|CM|CD|DC?C?C?|CC?C?)'
    content = re.sub(r'(?<![\w-])V\. (cholerae|parahaemolyticus|vulnificus|alginolyticus|hollisae|damsela|mimicus|fluvialis|furnisii|metschnikovii|cincinnatiensis)(?![\w-])', r'Vibrio \1', content)
    content = re.sub(r'(?<![\w-])H\. (ducreyi|parahaemolyticus|aegyptius|(para)?influenzae)(?![\w-])', r'Haemophilus \1', content)
    content = re.sub(r'(?<![\w-])M\. (tuberculosis|leprae|ulcerans)(?![\w-])', r'Mycobacterium \1', content)
    content = re.sub(r'(?<![\w-])SAG\.M\.(?![\w-])', r'solución salina-adenina-glucosa-manitol', content)
    content = re.sub(r'(?<![\w-])g\.( d\.)? l\.(?![\w-])', r'grado de libertad', content)
    content = re.sub(r'(?<![\w-])H\.( capsulatum)(?![\w-])', r'histoplasma\1', content)
    content = re.sub(r'(?<![\w-])(p(or |[.,] ?))?[Ee]j[.:]', r'por ejemplo', content)
    content = re.sub(r'(?<![\w-])H\.( pylori)(?![\w-])', r'Helicobacter\1', content)
    content = re.sub(r'(?<![\w-])EE\. UU[^\w](?![\w-])', r'Estados Unidos', content)
    content = re.sub(r'(?<![\w-])p\.m\.(?![\w-])', r'después del mediodía', content)
    content = re.sub(r'(?<![\w-])d\. C\.(?![\w-])', r'después de Cristo', content)
    content = re.sub(r'(?<![\w-])a\.m\.(?![\w-])', r'antes del mediodía', content)
    content = re.sub(r'(?<![\w-])a\. C\.(?![\w-])', r'antes de Cristo', content)
    content = re.sub(rf'(?<![\w-])s\. {ROMANO}(?![\w-])', r'siglo \1', content)
    content = re.sub(r'(?<![\w-])(A|a)br\.(?![\w-])', r'abreviatura', content)
    content = re.sub(r'(?<![\w-])S(IN|in)\.(?![\w-])', r'Sinónimos', content)
    content = re.sub(r'(?<![\w-])i\.m\.(?![\w-])', r'intramuscular', content)
    content = re.sub(r'(?<![\w-])coloq\.(?![\w-])', r'Coloquial', content)
    content = re.sub(r'(?<![\w-])etc\.([,)])(?![\w-])', r'\1', content)
    content = re.sub(r'(?<![\w-])desus\.(?![\w-])', r'Desuso', content)
    content = re.sub(r'(?<![\w-])Fórm\.(?![\w-])', r'fórmula', content)
    content = re.sub(r'(?<![\w-])loc\.(?![\w-])', r'Locución', content)
    content = re.sub(r'(?<![\w-])O(BS|bs)\.:?(?![\w-])', r'', content)
    content = re.sub(r'(?<![\w-])ingl\.(?![\w-])', r'ingles', content)
    content = re.sub(r'(?<![\w-])etc\.(?![\w-])', r'.', content)
    content = re.sub(r'(?<![\w-])Símb\. ', r'símbolo ', content)
    content = re.sub(r'(?<![\w-])Dra\. ', r'doctora ', content)
    content = re.sub(r'(?<![\w-])Dr\. ', r'doctor ', content)
    content = re.sub(r'(?<![\w-])St\.', r'San', content)
    return content
