import re

def sustituir_simbolos(content):
    content = re.sub(r'(?<![\w-])(Hz|[Hh]er(z|cio|tz(ios?)?))(?![\w-])', r'hercios', content)
    content = re.sub(r'(?<=/)[Ll](?=[ .,;&)-])|(?<![\w-])[Ll](?=[,/])', r'litros', content)
    content = re.sub(r'(?<=[\d}])( )m(?![\w-])|(?<![\w-])()m(?=\^)', r'\1metros', content)
    content = re.sub(r'(?<![\w-])mm[Hh]g(?![\w-])', r'milímetros de mercurio', content)
    content = re.sub(r'(?<=[/\d}]) ?gr?(?![\w-])|(?<!\w)gr?(?=/)', r' gramos', content)
    content = re.sub(r'(?<![a-zA-Z-])[µμμ][lL](?![\w-])', r' microlitros', content)
    content = re.sub(r'(?<![a-zA-Z-])[µμμ]Wb(?![\w-])', r' micro-webers', content)
    content = re.sub(r'(?<![a-zA-Z-])[µμμ]mol(?![\w-])', r' micromoles', content)
    content = re.sub(r'(?<![a-zA-Z-])[µμμ]V(?![\w-])', r' microvoltios', content)
    content = re.sub(r'(?<![a-zA-Z-])[µμμ]g(?![\w-])', r' microgramos', content)
    content = re.sub(r'(?<![a-zA-Z-])[µμμ]m(?![\w-])', r' micrómetros', content)
    content = re.sub(r'(?<![\w-])mmol([^.])(?![\w-])', r'milimoles\1', content)
    content = re.sub(r'(?<![\w-])mOsm(ol)?(?![\w-])', r'miliosmoles', content)
    content = re.sub(r'(?<![\w-])3D(?=[ .,;)-])', r'tridimensional', content)
    content = re.sub(r'(?<![\w-])(kD|Kd)(?![\w-])', r'kilodaltons', content)
    content = re.sub(r'(?<![a-zA-Z])=(?![a-zA-Z])', r' igual a ', content)
    content = re.sub(r'(?<![\w-])cms?(?![\w-])', r'centímetros', content)
    content = re.sub(r'(?<![\w-])d[Ll](?![\w-])', r'decilitros', content)
    content = re.sub(r'(?<![\w-])m[Ll](?![\w-])', r'mililitros', content)
    content = re.sub(r'(?<![\w-])pb(?![\w-])', r'par de bases', content)
    content = re.sub(r'(?<![\w-])≠(?![\w-])', r' distinto de ', content)
    content = re.sub(r'(°|º|\^{o}) ?C', r' grados centígrados', content)
    content = re.sub(r'(?<![\w-])kDa(?![\w-])', r'kilodalton', content)
    content = re.sub(r'(?<![\w-])mV(?![\w-])', r'milivoltios', content)
    content = re.sub(r'(?<![\w-])mill(?![\w-])', r'millones', content)
    content = re.sub(r'(?<![\w-])mg(?![\w-])', r'miligramos', content)
    content = re.sub(r'(?<![\w-])kg(?![\w-])', r'kilogramos', content)
    content = re.sub(r'(?<![\w-])mm(?![\w-])', r'milímetros', content)
    content = re.sub(r'(?<![\w-])ng(?![\w-])', r'nanogramos', content)
    content = re.sub(r'(?<![\w-])nm(?![\w-])', r'nanometros', content)
    content = re.sub(r'(?<![\w-])dB(?![\w-])', r'decibelios', content)
    content = re.sub(r'(?<![\w-])Kb(?![\w-])', r'kilobases', content)
    content = re.sub(r'(?<![\w-])y [-/] o(?![\w-])', r'y/o', content)
    content = re.sub(r'(?<![\w-])min(?![\w-])', r'minutos', content)
    content = re.sub(r'(?<![\w-])Hg(?![\w-])', r'mercurio', content)
    content = re.sub(r'(?<![\w-])±(?![\w-])', r'más-menos', content)
    content = re.sub(r'([a-zA-Z])([αβßγελδζµκ])', r'\1_\2', content)
    content = re.sub(r'([αβßγελδζµκ])([a-zA-Z])', r'\1_\2', content)
    content = re.sub(r'(?<![(\w-])h(?![\n\w-])', r'horas', content)
    content = re.sub(r'(?<![\w-])gr(?![\w-])', r'griego', content)
    content = re.sub(r'(?<![\w-])Wb(?![\w-])', r'weber', content)
    content = re.sub(r'(?<=\w)\+(?!\w)', r' positivo ', content)
    content = re.sub(r'(?<!\w)>(?!\w)', r'mayor que', content)
    content = re.sub(r'(?<!\w)<(?!\w)', r'menor que', content)
    content = re.sub(r'(?<!\w)Rh(?!\w)', r'Rhesus', content)
    content = re.sub(r'≤', r' menor o igual que ', content)
    content = re.sub(r'≥', r' mayor o igual que ', content)
    content = re.sub(r'°F', r' grados fahrenheit', content)
    content = re.sub(r'\.{3}', r', etcétera. ', content)
    content = re.sub(r'\^{\+}', r' positivo ', content)
    content = re.sub(r'\^{-}', r' negativo ', content)
    content = re.sub(r'α|&alpha;', r'Alpha', content)
    content = re.sub(r'β|ß|&beta;', r'Beta', content)
    content = re.sub(r'γ|&gamma;', r'Gamma', content)
    content = re.sub(r'¾', r'tres cuartos', content)
    content = re.sub(r'®', r' registrado', content)
    content = re.sub(r'º ?K', r' kelvin', content)
    content = re.sub(r'[º°]', r' grados', content)
    content = re.sub(r'¼', r'un cuarto', content)
    content = re.sub(r'[ÄÅåàãâā]', r'a', content)#Tal vez
    content = re.sub(r'[èëêĕěē]', r'e', content)#Tal vez
    content = re.sub(r'[òøöōôő]', r'o', content)#Tal vez
    content = re.sub(r'[δΔ]', r'Delta', content)
    content = re.sub(r'[ωΩ]', r'Omega', content)
    content = re.sub(r'[Σς]', r'Sigma', content)
    content = re.sub(r'∞', r'infinito', content)
    content = re.sub(r'ε', r'Épsilon', content)
    content = re.sub(r'ό', r'Ómicron', content)
    content = re.sub(r'[ιί]', r'Iota', content)
    content = re.sub(r'[µμμ]', r'Mu', content)
    content = re.sub(r'\+', r' más ', content)
    content = re.sub(r'λ', r'Lambda', content)
    content = re.sub(r'κ', r'Kappa', content)
    content = re.sub(r'θ', r'Theta', content)
    content = re.sub(r'[ìīï]', r'i', content)#Tal vez
    content = re.sub(r'[ùцŭ]', r'u', content)#Tal vez
    content = re.sub(r'ζ', r'Zeta', content)
    content = re.sub(r'[łл]', r'l', content)#Tal vez
    content = re.sub(r'[ńη]', r'n', content)#Tal vez
    content = re.sub(r'²', r'^{2}', content)
    content = re.sub(r'³', r'^{3}', content)
    content = re.sub(r'₃', r'_{3}', content)
    content = re.sub(r'τ', r'Tau', content)
    content = re.sub(r'χ', r'Chi', content)
    content = re.sub(r'×', r'por', content)
    content = re.sub(r'š', r'sch', content)
    content = re.sub(r'π', r'pi', content)
    content = re.sub(r'æ', r'ae', content)
    content = re.sub(r'ы', r'bi', content)
    content = re.sub(r'î', r'iu', content)
    content = re.sub(r'φ', r'Fi', content)
    content = re.sub(r'œ', r'oe', content)
    content = re.sub(r'Б', r'b', content)
    content = re.sub(r'ç', r'c', content)
    content = re.sub(r'ρ', r'p', content)
    content = re.sub(r'ş', r's', content)
    content = re.sub(r'т', r't', content)
    content = re.sub(r'ŷ', r'y', content)
    return content
